<?php

function custom_valdiation_address($address){
if(!empty($address)){
   // print $address;

  if(preg_match("/([%\$#@!`~&\*]+)/", $address)){
          form_set_error('',t('Do Not Allow Special Character in Address'));
  }
  else if(preg_match('/^(.)\1*$/', substr($address,0,3))){
        drupal_set_message(t('In Address there is Repataion of same charcter please check it'), 'warning');
    }
 }
}

function custom_valdiation_pincode($pin){
  $length = trim(strlen($pin));
  if($length > 6){
              form_set_error('',t('Pincode must be six character'));

  }

  
}

function custom_valdiation_aadhaar($aadhaar){
  if(!empty($aadhaar)){
       $val = ssid_verify($aadhaar);
           if ((!ctype_digit(str_replace(' ', '', $aadhaar)))) {
      form_set_error('',t('AAdhaar must be numeric'));
   }
  else if(preg_match('/\s/',$aadhaar)) {
        form_set_error('',t('Aadhaar Number Conatin Space Please remove the space'));
      }
      else if((strlen($aadhaar) > 12) || (strlen($aadhaar) < 12)){
       form_set_error('',t('Aadhaar must  be 12 character'));
       }
   else if(!$val){
          form_set_error('',t('Not a Valid AAdhaar'));
        }
      
   }
}

function custom_valdiation_eid($eid){

if (!empty($eid)) {   
       if ((!ctype_digit($eid))) {
      form_set_error('',t('EID must be numeric and Do not use Space'));
       }
       else if((strlen($number) > 28) || (strlen($number) < 28)){
       form_set_error('',t('EID must  be 28 character'));
       }
      
   }  
  
}

function custom_valdiation_name($name, $agency){
 if(!empty($name)){
      if (!ctype_alpha(str_replace(' ', '', $name))) {
           form_set_error('',t('only Alphabates are allowed in '.$agency));
     }
  }
}

function custom_valdiation_date(){

  
}

function custom_valdiation_election_card_no($election_no){
if(!empty($election_no)){
      if((strlen($election_no) > 10) || (strlen($election_no) < 10)){
              form_set_error('',t('Election Number must be of 10 chararacter'));
}
else if(preg_match('/\s/',$election_no)) {
        form_set_error('',t('Election Number Conatin Space Please remove the space'));
      }
else if ((ctype_digit($election_no))) {
      form_set_error('',t('Only Alphanumeric chararacter in  Election Card Number'));
       }
  }
}

function custom_valdiation_bank_name($b_name ,$name){
  if(!empty($b_name)){
      if (!ctype_alpha(str_replace(' ', '', $b_name))) {
           form_set_error('',t('only ALphabates are allowed in '.$name));
     }
  }
}

function custom_valdiation_ifsc_code($ifsc){

  if(!empty($ifsc)){
    if((strlen($ifsc) > 11) || (strlen($ifsc) < 11)){
       form_set_error('',t('IFSC Code Only contain 11 Character'));
       }
     else if(preg_match('/\s/',$ifsc)) {
        form_set_error('',t('IFSC Code Conatin Space Please remove the space'));
      }
      else if(!ctype_alpha(substr($ifsc,0,4))){
        form_set_error('',t('First four character must be alphabate in IFSC code'));
       }
       else if (substr($ifsc,4,1) != '0'){
              form_set_error('',t('The Fifth Character Must be  0 in IFSC Code'));
     }      
  }  
}

function custom_valdiation_mobile($number){

   if (!empty($number)) {   
       if ((!ctype_digit($number))) {
      form_set_error('field_mobile_number',t('mobile number must be numeric and Do not use Space'));
       }
       else if((strlen($number) > 10) || (strlen($number) < 10)){
       form_set_error('',t('mobile number must 10 digit'));
       }
       else if(preg_match('/^(.)\1*$/', $number)){
            drupal_set_message(t('All are same character in mobile number.'), 'warning');
       }
   }  
}

function custom_valdiation_ac($ac){

   if (!empty($ac)) {   
       if ((!ctype_digit($ac))) {
      form_set_error('field_mobile_number',t('A/c No must be numeric and do not contain space'));
       }
     }
   }

